### ISSUE TITLE
Thank you, and please keep forward for this extison. Cheers! 

### ISSUE THREAD

**Issue by hrenx** [shadowndacorner/vscode-easymotion#2]
It's really is a very good extension, cheers! I hope there are will have more good features. I really like it, it's really good for someone who don't want to learn vim but want to use vim-easymotion, it allows me to use the mouse less and it's also very good for my recovery from cervical spondylosis.

**Comment by shadowndacorner** [comment]
Glad to hear that you like it!  Feel free to leave a rating in the [marketplace](https://marketplace.visualstudio.com/items?itemName=shadowndacorner.vscode-easymotion) as well.

As far as new features go, I'm using it daily and adding features as I feel like I need them.  If you think of an improvement you'd like to see, feel free to open an issue and I'll try to get to it when I have time.
