### ISSUE TITLE
Illegible due to hard-coded tag/foreground color

### ISSUE THREAD

**Issue by riotrah** [shadowndacorner/vscode-easymotion#5]
![Screenshot 2023-04-17 at 7 07 29 PM](https://user-images.githubusercontent.com/22646419/232651626-ed5f35dc-a1cd-45d7-aa16-d9411b26ccaa.png)

This occurs due to the hardcoded tag color + light mode. Auto switching between light/dark modes is a popular, sorta recently available feature in vsc, so implementing support for this would be great.

I've seen/used various extensions that leverage mode-sensitive colors and as a user my fave config approach is as follows:

```jsonc
"vscode-easymotion.colors": {
    "dark": {
      "farForeground": "#FF0000",
      "nearForeground": "#FF0000"
    },
    "light": {
      "farForeground": "#FF0000",
      "nearForeground": "#FF0000"
    }
  }
```

or something like that.

---

Relevant APIs:

`vscode.window.activeColorTheme: ColorTheme`
`vscode.window.activeColorTheme.kind: 'Dark' | 'HighContrast' | 'Light'`

Maybe there's a way to simply make the colors an inversion of the background via CSS filters, but not sure if there is.

**Comment by shadowndacorner** [comment]
Thanks for bringing this to my attention, and for directing me to the relevant APIs!  I'll try to implement these changes some time this week, though I may not have time to do so until next week.  I'd also welcome a PR if you want to take a shot at implementing it yourself before I get around to it - I think it should be fairly straightforward to implement.

**Comment by riotrah** [comment]
Sounds like a plan, will attempt to beat you to it

**Comment by riotrah** [comment]
PR opened. I went with a different configuration shape, mostly to ease dev but keep things flexible, mostly accepting the same overrides your decoration styles already make use of. IDK if it's sensible to offer everything tho, eg `width`.
