### ISSUE TITLE
How to avoid key binding issues with vscodevim?

### ISSUE THREAD

**Issue by xinyuan96** [shadowndacorner/vscode-easymotion#7]
Hi,

I also installed vscodevim extension. But it has key conflict. 
If jumpToWord, it will show jump tag "h j k l" etc. but vscodevim already keys are already mapped those keys to vim cursor move.
How to resolve the above issue?
Kindly thanks for answering the question.

Thanks

**Comment by shadowndacorner** [comment]
Apologies for the delay on this, seems like I missed the notification and I don't check the issues frequently enough to have caught it sooner.

VSCodeVim has built-in support for Vim-style EasyMotion, which was actually the inspiration for this extension.  I'd recommend that you just use that as it is nicely integrated with the rest of VSCodeVim and is generally a bit more powerful than this extension as it is built around Vim-style navigation.  However, if you'd still prefer to use this extension, it should definitely be possible to expose the available keys as a config variable, which should allow you to disable hjkl.

If that's something you're interested in, I should have time to implement that in the next week.  If you're going to use EasyMotion as it's built into VSCodeVim, then I'll probably hold off on implementing it until someone else has a need for it.

Sorry again for the delayed response!

**Comment by shadowndacorner** [comment]
@xinyuan96 Since this issue has been inactive for several months, I'm going to go ahead and close it.  Feel free to reopen if my response was not satisfactory!
